### ISSUE TITLE
Article Bottom border needs to be moved to a different element

### ISSUE THREAD

**Issue by nfon-christophe** [saga-nfon/adapt-nfon-theme#1]
The article bottom border has been set against against `.article__container`, but should be set against `.article__inner` instead.

This is the correction I have made in customer CSS to correct the issue:

```CSS
.article__inner {border-bottom: #004563 100px solid;}
.article__container {border-bottom: 0px;}
```
