### ISSUE TITLE
Narrative Component - Content Title

### ISSUE THREAD

**Issue by nfon-christophe** [saga-nfon/adapt-nfon-theme#3]
When "Move navigation to text area" is selected, the content title is too close to the navigation button and needs to be moved down a bit.

This is the quick fix I have currently implemented:

```css
.narrative__content-title { margin-top: 15px;}
```

However, this should only apply if the navigation in in the text area.
