### ISSUE TITLE
Expose Component - CSS fixes

### ISSUE THREAD

**Issue by nfon-christophe** [saga-nfon/adapt-nfon-theme#6]
There are a couple of minor issues we have found so far with the Expose component plugin:

```css
.expose-item {margin-bottom: 1rem;}
.expose-item-content .expose-item-body {word-break: break-word;}
```

Could this be corrected?
